name: Producer Upload Workflow

on:
  push:
    branches: [main]
    paths:
      - '**.csv'

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::200110254415:role/proyect-user2
          aws-region: us-east-1

      - name: Instalar dependencias
        run: pip install boto3

      - name: Ejecutar producer.py si hay .csv
        run: |
          for file in *.csv; do
            echo "Procesando $file"
            python3 producer.py "$file"
          done
#prueba