name: Upload CSV to S3

on:
  push:
    paths:
      - '*.csv'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install boto3
        run: pip install boto3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::200110254415:role/proyect-user2
          aws-region: us-east-1

      - name: Run producer script
        run: python3 producer.py prueba.csv
        env:
          INPUT_BUCKET: upeu-producer-x-bucket-1
