name: Upload CSV to S3

on:
  push:
    paths:
      - '*.csv'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install boto3
        run: pip install boto3

      - name: Run producer script
        run: python producer.py prueba.csv
        env:
          INPUT_BUCKET: upeu-producer-x-bucket-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
